# Generated by Django 4.0.4 on 2022-08-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
