# Generated by Django 4.0.4 on 2022-08-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
