# Generated by Django 4.0.4 on 2022-08-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('quiz', '0002_quiz_started'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'quiz', 'id')},
        ),
    ]
