# Generated by Django 4.0.4 on 2022-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_total_marks_alter_question_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='publish_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
