# Generated by Django 4.0.4 on 2022-08-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('quiz', '0003_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'quiz', 'question')},
        ),
    ]
