# Generated by Django 4.0.4 on 2022-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_studentanswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
