# Generated by Django 4.0.4 on 2022-07-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
