# Generated by Django 4.0.4 on 2022-08-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_absence',
        ),
    ]
